version: '3'
services:

  nginx:
    image: nginx:alpine
    container_name: app_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel:/var/www/app/laravel
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app

  certbot:
    image: certbot/certbot
    container_name: app_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

networks:
  app:
    driver: bridge