version: '3'
services:

  nginx:
    image: nginx:alpine
    container_name: app_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel:/var/www/app/laravel
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app

  pgsql:
    container_name: app_postgres
    restart: unless-stopped
    image: postgres:14
    ports:
      - '127.0.0.1:5432:5432'
    env_file:
      - ./pgsql/.env
    volumes:
      - pgsql-volume:/var/lib/postgresql/data
    networks:
      - app

  laravel:
    container_name: app_laravel
    restart: unless-stopped
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/app/laravel
    networks:
      - app
    command: composer install

  redis:
    container_name: app_redis
    restart: unless-stopped
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  pgsql-volume:
    driver: local
  redis-volume:
    driver: local