version: '3'
services:

  redis:
    container_name: app_redis
    restart: unless-stopped
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    networks:
      - app

volumes:
  redis-volume:
    driver: local